import { ComponentType } from '../types/component';

export const componentLibrary: Record<string, ComponentType[]> = {
  'Inputs': [
    {
      name: 'text_input',
      display_name: 'Text Input',
      description: 'Input text data into the flow',
      category: 'Inputs',
      icon: 'Type',
      version: '1.0.0',
      inputs: [
        {
          id: '1',
          name: 'value',
          display_name: 'Text',
          type: 'Text',
          description: 'Text value to input',
          required: true,
          multiple: false,
          advanced: false,
        },
      ],
      outputs: [
        {
          id: '2',
          name: 'text',
          display_name: 'Text',
          type: 'Text',
          description: 'Output text',
          required: true,
          multiple: false,
          advanced: false,
        },
      ],
    },
    {
      name: 'chat_input',
      display_name: 'Chat Input',
      description: 'Input for chat messages with optional session management',
      category: 'Inputs',
      icon: 'MessageCircle',
      version: '1.0.0',
      inputs: [
        {
          id: '1',
          name: 'message',
          display_name: 'Message',
          type: 'Text',
          description: 'User message',
          required: true,
          multiple: false,
          advanced: false,
        },
        {
          id: '2',
          name: 'session_id',
          display_name: 'Session ID',
          type: 'Text',
          description: 'Session identifier for conversation context',
          required: false,
          multiple: false,
          advanced: false,
        },
      ],
      outputs: [
        {
          id: '3',
          name: 'message',
          display_name: 'Message',
          type: 'Message',
          description: 'Formatted chat message',
          required: true,
          multiple: false,
          advanced: false,
        },
      ],
    },
  ],
  'Language Models': [
    {
      name: 'openai_llm',
      display_name: 'OpenAI LLM',
      description: 'OpenAI language model for text generation',
      category: 'Language Models',
      icon: 'MessageSquare',
      version: '1.0.0',
      inputs: [
        {
          id: '1',
          name: 'prompt',
          display_name: 'Prompt',
          type: 'Text',
          description: 'Input prompt for the model',
          required: true,
          multiple: false,
          advanced: false,
        },
        {
          id: '2',
          name: 'model',
          display_name: 'Model',
          type: 'Text',
          description: 'Model to use',
          default: 'gpt-4',
          options: ['gpt-4', 'gpt-4-turbo-preview', 'gpt-3.5-turbo'],
          required: true,
          multiple: false,
          advanced: false,
        },
        {
          id: '3',
          name: 'temperature',
          display_name: 'Temperature',
          type: 'Number',
          description: 'Sampling temperature (0-2)',
          default: 0.7,
          required: false,
          multiple: false,
          advanced: false,
        },
        {
          id: '4',
          name: 'api_key',
          display_name: 'API Key',
          type: 'Text',
          description: 'OpenAI API key',
          required: false,
          multiple: false,
          advanced: true,
        },
      ],
      outputs: [
        {
          id: '5',
          name: 'response',
          display_name: 'Response',
          type: 'Text',
          description: 'Generated text response',
          required: true,
          multiple: false,
          advanced: false,
        },
        {
          id: '6',
          name: 'usage',
          display_name: 'Usage',
          type: 'Data',
          description: 'Token usage information',
          required: true,
          multiple: false,
          advanced: false,
        },
      ],
    },
  ],
  'Tools': [
    {
      name: 'web_search',
      display_name: 'Web Search',
      description: 'Search the web for information',
      category: 'Tools',
      icon: 'Search',
      version: '1.0.0',
      inputs: [
        {
          id: '1',
          name: 'query',
          display_name: 'Query',
          type: 'Text',
          description: 'Search query',
          required: true,
          multiple: false,
          advanced: false,
        },
      ],
      outputs: [
        {
          id: '2',
          name: 'results',
          display_name: 'Results',
          type: 'Data',
          description: 'Search results',
          required: true,
          multiple: false,
          advanced: false,
        },
      ],
    },
  ],
  'Outputs': [
    {
      name: 'text_output',
      display_name: 'Text Output',
      description: 'Output text from the flow',
      category: 'Outputs',
      icon: 'FileText',
      version: '1.0.0',
      inputs: [
        {
          id: '1',
          name: 'text',
          display_name: 'Text',
          type: 'Text',
          description: 'Text to output',
          required: true,
          multiple: false,
          advanced: false,
        },
      ],
      outputs: [],
    },
  ],
};
